### PR TITLE
CSI 1057 handle self transaction correctly

### PR DESCRIPTION
**Pull request by HarishRocks**

### CODE REVIEW

**Comment by irshadCypherock** [comment]
Task linked: [CSI-1057 Handle self transaction appropriately](https://app.clickup.com/t/37308523/CSI-1057)

**Comment by HarishRocks** [comment]
@irshadCypherock 
pls see if this fits at both the place

**Comment by HarishRocks** [comment]
Bug marked as `not an issue`

**Comment by HarishRocks** [comment]
The underlying bug was decided to be marked as `not an issue`

**Pull request closed without merging**
